#!/usr/bin/env bash
# Generate ortie + himalaya config for an Outlook mailbox that uses OAuth 2.0.
#
# Ortie owns the OAuth grant and token refresh. Himalaya v1.2.0 consumes the
# access token through `backend.auth.access-token.cmd` (XOAUTH2). This script
# is idempotent: existing account sections are left untouched.
#
# Required environment:
#   EMAIL_OUTLOOK_ADDRESS  Mailbox address used as IMAP/SMTP login.
#
# Optional environment:
#   EMAIL_OUTLOOK_ACCOUNT_NAME  Himalaya/ortie account id (default: outlook).
#   EMAIL_OUTLOOK_DISPLAY_NAME  From-header display name.
#   EMAIL_OUTLOOK_GRANT         device | authorization-code (default: device).
#   EMAIL_OUTLOOK_CLIENT_ID     Azure public client id (Thunderbird default).
#   EMAIL_OUTLOOK_IMAP_HOST     Default outlook.office365.com.
#   EMAIL_OUTLOOK_IMAP_PORT     Default 993.
#   EMAIL_OUTLOOK_SMTP_HOST     Default smtp.office365.com.
#   EMAIL_OUTLOOK_SMTP_PORT     Default 587.
#   HERMES_DATA                 Config root (default: /opt/data).
set -euo pipefail
umask 077

HERMES_DATA="${HERMES_DATA:-/opt/data}"
ADDRESS="${EMAIL_OUTLOOK_ADDRESS:-}"

if [[ -z "${ADDRESS}" ]]; then
  exit 0
fi

ACCT="${EMAIL_OUTLOOK_ACCOUNT_NAME:-outlook}"
DISPLAY_NAME="${EMAIL_OUTLOOK_DISPLAY_NAME:-${ADDRESS}}"
GRANT="${EMAIL_OUTLOOK_GRANT:-device}"
# Thunderbird public client registered for Outlook IMAP/SMTP (not Graph).
# Source: mozilla-central mailnews/base/src/OAuth2Providers.sys.mjs
CLIENT_ID="${EMAIL_OUTLOOK_CLIENT_ID:-9e5f94bc-e8a4-4e73-b8be-63364c29d753}"
IMAP_HOST="${EMAIL_OUTLOOK_IMAP_HOST:-outlook.office365.com}"
IMAP_PORT="${EMAIL_OUTLOOK_IMAP_PORT:-993}"
SMTP_HOST="${EMAIL_OUTLOOK_SMTP_HOST:-smtp.office365.com}"
SMTP_PORT="${EMAIL_OUTLOOK_SMTP_PORT:-587}"

if [[ ! "${ACCT}" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "   ❌ EMAIL_OUTLOOK_ACCOUNT_NAME must be alphanumeric, '_' or '-': ${ACCT}" >&2
  exit 1
fi

if [[ "${GRANT}" != "device" && "${GRANT}" != "authorization-code" ]]; then
  echo "   ❌ EMAIL_OUTLOOK_GRANT must be 'device' or 'authorization-code': ${GRANT}" >&2
  exit 1
fi

ORTIE_DIR="${HERMES_DATA}/.config/ortie"
TOKEN_DIR="${ORTIE_DIR}/tokens"
TOKEN_FILE="${TOKEN_DIR}/${ACCT}.json"
ORTIE_CONFIG="${ORTIE_DIR}/config.toml"
HIMALAYA_CONFIG="${HERMES_DATA}/.config/himalaya/config.toml"

mkdir -p "${TOKEN_DIR}" "${HERMES_DATA}/.config/himalaya"
chmod 700 "${ORTIE_DIR}" "${TOKEN_DIR}"

# ── ortie account ─────────────────────────────────────────────
if [[ -f "${ORTIE_CONFIG}" ]] && grep -q "^\[accounts\.${ACCT}\]" "${ORTIE_CONFIG}"; then
  echo "   📧 ortie account '${ACCT}' already present — skip"
else
  if [[ "${GRANT}" == "device" ]]; then
    GRANT_BLOCK="$(cat << EOF
grant = "device"
endpoints.authorization = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
endpoints.token = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
endpoints.device-authorization = "https://login.microsoftonline.com/common/oauth2/v2.0/devicecode"
EOF
)"
  else
    GRANT_BLOCK="$(cat << EOF
grant = "authorization-code"
pkce = true
endpoints.authorization = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
endpoints.token = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
endpoints.redirection = "https://localhost"
EOF
)"
  fi

  if [[ ! -f "${ORTIE_CONFIG}" ]]; then
    cat > "${ORTIE_CONFIG}" << EOF
# Generated by configure-outlook.sh — Outlook IMAP/SMTP OAuth via ortie.
EOF
  fi

  cat >> "${ORTIE_CONFIG}" << EOF

[accounts.${ACCT}]
default = true
client-id = "${CLIENT_ID}"
${GRANT_BLOCK}
scopes = [
  "offline_access",
  "https://outlook.office.com/IMAP.AccessAsUser.All",
  "https://outlook.office.com/SMTP.Send",
]
auto-refresh = true
storage.read.command = ["cat", "${TOKEN_FILE}"]
storage.write.command = "umask 077 && cat > ${TOKEN_FILE}"
EOF
  chmod 600 "${ORTIE_CONFIG}"
  echo "   📧 ortie 已配置 — ${ADDRESS} (account: ${ACCT}, grant: ${GRANT})"
fi

# ── himalaya account ──────────────────────────────────────────
TOKEN_CMD="ortie -c ${ORTIE_CONFIG} token show -a ${ACCT}"

if [[ -f "${HIMALAYA_CONFIG}" ]] && grep -q "^\[accounts\.${ACCT}\]" "${HIMALAYA_CONFIG}"; then
  echo "   📧 himalaya account '${ACCT}' already present — skip"
else
  DEFAULT_FLAG="false"
  if [[ ! -f "${HIMALAYA_CONFIG}" ]] || ! grep -q "^\[accounts\." "${HIMALAYA_CONFIG}"; then
    DEFAULT_FLAG="true"
  fi
  mkdir -p "$(dirname "${HIMALAYA_CONFIG}")"
  cat >> "${HIMALAYA_CONFIG}" << EOF

[accounts.${ACCT}]
email = "${ADDRESS}"
display-name = "${DISPLAY_NAME}"
default = ${DEFAULT_FLAG}

backend.type = "imap"
backend.host = "${IMAP_HOST}"
backend.port = ${IMAP_PORT}
backend.encryption.type = "tls"
backend.login = "${ADDRESS}"
backend.auth.type = "oauth2"
backend.auth.method = "xoauth2"
backend.auth.client-id = "${CLIENT_ID}"
backend.auth.access-token.cmd = "${TOKEN_CMD}"

message.send.backend.type = "smtp"
message.send.backend.host = "${SMTP_HOST}"
message.send.backend.port = ${SMTP_PORT}
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "${ADDRESS}"
message.send.backend.auth.type = "oauth2"
message.send.backend.auth.method = "xoauth2"
message.send.backend.auth.client-id = "${CLIENT_ID}"
message.send.backend.auth.access-token.cmd = "${TOKEN_CMD}"
EOF
  chmod 600 "${HIMALAYA_CONFIG}"
  echo "   📧 himalaya 已配置 Outlook — ${ADDRESS} (account: ${ACCT})"
fi

if [[ -s "${TOKEN_FILE}" ]]; then
  echo "   🔑 Outlook OAuth token present — ${TOKEN_FILE}"
else
  echo "   ⚠️  Outlook OAuth 尚未授权。容器内一次性执行："
  echo "      ortie -c ${ORTIE_CONFIG} auth get -a ${ACCT}"
  if [[ "${GRANT}" == "device" ]]; then
    echo "      （device grant：打开 https://microsoft.com/devicelogin 并输入显示的代码）"
  else
    echo "      （authorization-code：用浏览器打开打印的 URL，再 ortie auth resume <redirect-uri>）"
  fi
fi
